// File Name: assign2_kmg221.cpp
//
// Author: Kody Gentry
// Date: 9/12/2019
// Assignment Number: 2
// CS 1428.003 Fall 2019
// Instructor: Jill Seaman
//
// Stadium Seating Statistics
#include <iostream>
using namespace std;
int main()
{
    //cost per ticket
    double costA, costB, costC;
    costA= 15.00;
    costB= 12.50;
    costC= 9.75;

    //input how many sold per ticket
    double soldA, soldB, soldC;
    cout << "Enter the number of class A tickets sold: " << endl;
    cin >> soldA;
    cout << "Enter the number of class B tickets sold: " << endl;
    cin >> soldB;
    cout << "Enter the number of class C tickets sold: " << endl;
    cin >> soldC;
    cout << endl;

    //total tickets sold
    int totalTickets;
    totalTickets= soldA+soldB+soldC;
    cout << "Total Tickets sold: " << totalTickets << endl;

    //income per ticket (gross)
    double grossA, grossB, grossC;
    grossA= costA*soldA;
    grossB= costB*soldB;
    grossC= costC*soldC;

    //total sales
    double totalSales;
    totalSales= grossA+grossB+grossC;
    cout << "Total Sales: $" << totalSales << endl;
    cout << endl;

    //percentages per ticket
    double percentA, percentB, percentC;
    percentA= (soldA/totalTickets)*100;
    percentB= (soldB/totalTickets)*100;
    percentC= (soldC/totalTickets)*100;
    cout << "Percent of total sales generated by: " << endl;
    cout << "Class A Seats: " << percentA << "%" << endl;
    cout << "Class B Seats: " << percentB << "%" << endl;
    cout << "Class C Seats: " << percentC << "%" << endl;
    return 0;
}